spring:
    application:
        name: SpringAIDemo
    ai:
        openai:
            api-key: ${OPEN_API_KEY}
            chat:
                options:
                    model: gpt-4.1-nano
        ollama:
            chat:
                options:
                    model: deepseek-coder-v2:16b